language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-cli -g
  
#before_script:
 # - npm install -g hexo

script:
  - hexo -v
  - npm run jsbuild
  - hexo clean
  - hexo generate

after_script:
  - node travis.js
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/goumang2010/hexo-wiki.git
