language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g hexo

script:
  - npm run jsbuild
  - hexo clean
  - hexo generate

after_script:
  - node travis.js "https://${GH_TOKEN}@${GH_REF}"
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/goumang2010/hexo-wiki.git