language: node_js
node_js: stable

before_install:
  - openssl aes-256-cbc -K $encrypted_7db6f52255d7_key -iv $encrypted_7db6f52255d7_iv -in deploy_key.enc -out deploy_key -d

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-cli -g
  
#before_script:
 # - npm install -g hexo

script:
  - hexo -v
  - npm run jsbuild
  - hexo clean
  - hexo generate

after_script:
  - node publish.js
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - ENCRYPTION_LABEL: 7db6f52255d7
   - GH_REF: github.com/goumang2010/hexo-wiki.git
